### ISSUE TITLE
Adding new grid breakpoint size doesn't clear properly with grid-uniform

### ISSUE THREAD

**Issue by blindMoe** [Shopify/Timber#344]
I added a new breakpoint size in timber.scss.liquid and although the CSS seems to be created properly it does not seem to work properly with grid-uniform as the clearfix-helper scss doesn't add in the new xlarge breakpoint.

Here is the code I added to timber.scss.liquid:

```scss
/*============================================================================
  #Breakpoint and Grid Variables
==============================================================================*/
$viewportIncrement: 1px;

$small: 480px;
$medium: 768px;
$large: 769px;
$xlarge: 1400px;

$postSmall: $small + $viewportIncrement;
$preMedium: $medium - $viewportIncrement;
$preLarge: $large - $viewportIncrement;
$preXlarge: $xlarge - $viewportIncrement;

/*================ The following are dependencies of csswizardry grid ================*/
$breakpoints: (
  'small' '(max-width: #{$small})',
  'medium' '(min-width: #{$postSmall}) and (max-width: #{$medium})',
  'medium-down' '(max-width: #{$medium})',
  'large' '(min-width: #{$large})',
  'xlarge' '(min-width: #{$xlarge})'
);
$breakpoint-has-widths: ('small', 'medium', 'medium-down', 'large', 'xlarge');
$breakpoint-has-push:  ('medium', 'medium-down', 'large', 'xlarge');
$breakpoint-has-pull:  ('medium', 'medium-down', 'large', 'xlarge');
```

Modification to product-grid-item.liquid:

```liquid
{% unless grid_item_width %}
  {% assign grid_item_width = 'xlarge--one-quarter large--one-third medium--one-half' %}
{% endunless %}
```

Steps to reproduce:
1. Clone the repo
2. Add the breakpoint using the code above
3. Modify 'snippets/product-grid-item.liquid' using the code above.
4. Stretch browser window wider than 1400px on a collection page where more than 4 products are listed.

If you open the browser window above 1400px you will see that only 3 products are shown on one line due to the clearfix applied to the rule ".grid-uniform .large--one-third:nth-child(3n+1)"

It does not seem like any of the xlarge breakpoints are added to the clearfix-helper rule.  Am I missing something?

**Comment by cshold** [comment]
If you change the large breakpoint to:
`'large' '(min-width: #{$large}) and (max-width: #{$preXlarge})',` it looks to fix the `grid-uniform` issue. There may be other unintended consequences for that though. I'll see if I can make a more streamlined approach though. Closing for now.

**Comment by sydneykaiserman** [comment]
The above-mentioned fix unfortunately brakes the grid on all pages expect for collection pages. I love Timber but the inability to add a breakpoints is a real problem I think. Adding breakpoints is especially important for collection pages which heavily rely on the grid. Is there another solution for adding breakpoints?

**Comment by anisval** [comment]
I just came out with a workaround that may be useful for your use case. With the idea from @cshold the clearfix problem is gone but the whole helper classes (hide, show, display-table...) will be "broken". Everywhere where `large--*` appears, should be added a `xlarge--*` and that would be too much work.

What I have done is following:
```scss
/*============================================================================
  #Breakpoint and Grid Variables
==============================================================================*/
$viewportIncrement: 1px;

$small: 480px;
$medium: 768px;
$large: 769px;
$xlarge: 1110px;

$postSmall: $small + $viewportIncrement;
$preMedium: $medium - $viewportIncrement;
$preLarge: $large - $viewportIncrement;
$preXLarge: $xlarge - $viewportIncrement;

/*================ The following are dependencies of csswizardry grid ================*/
$breakpoints: (
  'small' '(max-width: #{$small})',
  'medium' '(min-width: #{$postSmall}) and (max-width: #{$medium})',
  'medium-down' '(max-width: #{$medium})',
  'large' '(min-width: #{$large})',
  'large-to-xlarge' '(min-width: #{$large}) and (max-width: #{$preXLarge})',
  'xlarge' '(min-width: #{$xlarge})'
);
$breakpoint-has-widths: ('small', 'medium', 'medium-down', 'large', 'large-to-xlarge', 'xlarge');
$breakpoint-has-push:  ('medium', 'medium-down', 'large');
$breakpoint-has-pull:  ('medium', 'medium-down', 'large');
```

With this code, `large` classes will still be working as expected and you would just need following classes in the collection pages

```liquid
xlarge--one-quarter large-to-xlarge--one-third medium--one-half
```
